### ISSUE TITLE
Implement delete metadata from server in build.gradle

### ISSUE THREAD

**Issue by SergeyTrusov** [SergeyTrusov/sf-apex-mapper#1]

**Comment by RasMisha** [comment]
https://stackoverflow.com/questions/28940473/gradle-get-ant-task-output/28942219

**Comment by SergeyTrusov** [comment]
Delete Metadata functionality implemented only for type in common.sf.properties.

**Comment by SergeyTrusov** [comment]
Fixed in https://github.com/SergeyTrusov/sf-build-scripts
